import QuickLook
import SwiftUI
import CoreImage.CIFilterBuiltins
import UniformTypeIdentifiers

struct JourneyView: View {
    @EnvironmentObject private var store: AppStore
    @State private var journey: JourneyGraph?; @State private var mode = 0; @State private var query = ""; @State private var loading = true
    private var nodes: [JourneyNode] { journey?.nodes.filter { query.isEmpty || $0.label.localizedCaseInsensitiveContains(query) || $0.category.localizedCaseInsensitiveContains(query) } ?? [] }
    var body: some View { VStack { Picker("View", selection: $mode) { Text("Graph").tag(0); Text("Structured").tag(1) }.pickerStyle(.segmented).padding(.horizontal); if loading { Spacer(); ProgressView(); Spacer() } else if mode == 0 { JourneyGraphCanvas(nodes: nodes, edges: journey?.edges ?? []).padding() } else { List { if let journey { Section("Overview") { LabeledContent("Profile", value: journey.profile); LabeledContent("Nodes", value: "\(journey.nodes.count)"); LabeledContent("Connections", value: "\(journey.edges.count)") }; ForEach(Dictionary(grouping: nodes, by: { $0.category.nilIfEmpty ?? $0.kind }).keys.sorted(), id: \.self) { category in Section(category.capitalized) { ForEach(nodes.filter { ($0.category.nilIfEmpty ?? $0.kind) == category }) { node in HStack { Image(systemName: node.kind == "memory" ? "brain.head.profile" : "sparkles"); VStack(alignment: .leading) { Text(node.label); Text("\(node.kind) · \(node.useCount) uses").font(.caption).foregroundStyle(.secondary) }; Spacer(); if node.pinned { Image(systemName: "pin.fill") } } } } } } } } }.navigationTitle(NavDestination.journey.title).navigationBarTitleDisplayMode(.inline).searchable(text: $query).refreshable { await load() }.task { await load() } }
    private func load() async { loading = true; do { journey = try await store.api.journey() } catch { store.errorMessage = error.localizedDescription }; loading = false }
}

private struct JourneyGraphCanvas: View {
    let nodes: [JourneyNode]; let edges: [JourneyEdge]
    var body: some View { GeometryReader { geo in ZStack { Canvas { context, size in let points = positions(size); for edge in edges { if let a = points[edge.source], let b = points[edge.target] { var path = Path(); path.move(to: a); path.addLine(to: b); context.stroke(path, with: .color(.secondary.opacity(0.28)), lineWidth: 1) } } }; ForEach(Array(nodes.prefix(36).enumerated()), id: \.element.id) { index, node in let p = point(index, count: min(nodes.count, 36), size: geo.size); VStack(spacing: 3) { Circle().fill(node.kind == "memory" ? Color.purple : Color.blue).frame(width: node.pinned ? 22 : 16, height: node.pinned ? 22 : 16); Text(node.label).font(.caption2).lineLimit(2).frame(width: 82) }.position(p) } }.accessibilityElement(children: .contain) }.overlay { if nodes.isEmpty { ContentUnavailableView("No journey data", systemImage: "point.3.connected.trianglepath.dotted") } } }
    private func point(_ index: Int, count: Int, size: CGSize) -> CGPoint { let angle = Double(index) / Double(max(count, 1)) * .pi * 2; let ring = CGFloat(0.35 + Double(index % 3) * 0.13); return CGPoint(x: size.width / 2 + CGFloat(cos(angle)) * size.width * ring, y: size.height / 2 + CGFloat(sin(angle)) * size.height * ring) }
    private func positions(_ size: CGSize) -> [String: CGPoint] { Dictionary(uniqueKeysWithValues: Array(nodes.prefix(36).enumerated()).map { ($0.element.id, point($0.offset, count: min(nodes.count, 36), size: size)) }) }
}

struct SkillUsageView: View {
    @EnvironmentObject private var store: AppStore
    @State private var days = 7; @State private var stats: SkillUsageStats?
    var body: some View { List { Picker("Period", selection: $days) { Text("7 days").tag(7); Text("30 days").tag(30); Text("90 days").tag(90) }.pickerStyle(.segmented); if let stats { Section("Summary") { HStack { UsageMetric(title: "Loads", value: stats.totalLoads); UsageMetric(title: "Edits", value: stats.totalEdits); UsageMetric(title: "Skills", value: stats.distinct) } }; Section("Top skills") { ForEach(stats.top) { row in VStack(alignment: .leading, spacing: 7) { HStack { Text(row.id).font(.headline); Spacer(); Text("\(row.total)").font(.headline.monospacedDigit()) }; ProgressView(value: min(row.percentage, 100), total: 100).tint(.indigo); Text("\(row.views) loads · \(row.edits) edits").font(.caption).foregroundStyle(.secondary) } } }; Section("Daily activity") { ForEach(stats.daily.indices, id: \.self) { i in let day = stats.daily[i]; LabeledContent(day.string("date"), value: "\(day.int("total_count"))") } } } else { ProgressView() } }.navigationTitle(NavDestination.skillsUsage.title).navigationBarTitleDisplayMode(.inline).task(id: days) { await load() }.refreshable { await load() } }
    private func load() async { do { stats = try await store.api.skillUsage(days: days) } catch { store.errorMessage = error.localizedDescription } }
}
private struct UsageMetric: View { let title: LocalizedStringKey; let value: Int; var body: some View { VStack { Text("\(value)").font(.title2.bold().monospacedDigit()); Text(title).font(.caption).foregroundStyle(.secondary) }.frame(maxWidth: .infinity) } }

struct WebhooksView: View {
    @EnvironmentObject private var store: AppStore
    @State private var endpoints: [WebhookEndpoint] = []; @State private var editing: WebhookEndpoint?; @State private var creating = false; @State private var target = ""; @State private var events: [JSON] = []
    var body: some View { List { Section("Endpoints") { ForEach(endpoints) { item in Button { editing = item } label: { VStack(alignment: .leading, spacing: 4) { HStack { Text(item.name).font(.headline); Spacer(); StatusPill(text: item.runtime.string("state").nilIfEmpty ?? (item.enabled ? "enabled" : "disabled"), color: item.runtime.string("state") == "success" ? .green : .secondary) }; Text(item.url).font(.caption).foregroundStyle(.secondary).lineLimit(1); Text(item.events.joined(separator: " · ")).font(.caption2).foregroundStyle(.tertiary).lineLimit(2) } }.buttonStyle(.plain).swipeActions { Button(role: .destructive) { Task { await delete(item) } } label: { Label("Delete", systemImage: "trash") }; Button { Task { await test(item) } } label: { Label("Test", systemImage: "bolt") }.tint(.blue) } } }; Section("Local test target") { Text(target).font(.caption).textSelection(.enabled); Button("Clear events", role: .destructive) { Task { await store.attempt({ try await store.api.clearLocalWebhookEvents() }); await loadLocal() } }; ForEach(events.indices, id: \.self) { i in VStack(alignment: .leading) { Text(events[i].string("event")).font(.headline); Text(events[i].string("received_at")).font(.caption).foregroundStyle(.secondary); Text(events[i].string("event_id")).font(.caption2).textSelection(.enabled) } } } }.navigationTitle("Webhooks").toolbar { Button { creating = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $creating) { WebhookEditor(item: nil) { await load() } }.sheet(item: $editing) { item in WebhookEditor(item: item) { await load() } }.task { await load(); await loadLocal() }.refreshable { await load(); await loadLocal() } }
    private func load() async { do { endpoints = try await store.api.webhookEndpoints() } catch { store.errorMessage = error.localizedDescription } }
    private func loadLocal() async { target = (await store.attempt({ try await store.api.localWebhookTarget().string("url") })) ?? ""; events = (await store.attempt({ try await store.api.localWebhookEvents() })) ?? [] }
    private func delete(_ item: WebhookEndpoint) async { do { try await store.api.deleteWebhook(item.id); await load() } catch { store.errorMessage = error.localizedDescription } }
    private func test(_ item: WebhookEndpoint) async { do { let result = try await store.api.testWebhook(item.id); store.notify(result.bool("ok") ? String(localized: "Webhook delivered") : result.string("error").nilIfEmpty ?? String(localized: "Webhook failed")); await load() } catch { store.errorMessage = error.localizedDescription } }
}

private struct WebhookEditor: View {
    @EnvironmentObject private var store: AppStore; @Environment(\.dismiss) private var dismiss
    let item: WebhookEndpoint?; let reload: () async -> Void
    @State private var name = ""; @State private var url = ""; @State private var secret = ""; @State private var enabled = true; @State private var includeContent = false; @State private var includeUser = false; @State private var privateNetwork = false; @State private var retries = 3; @State private var selected: Set<String> = ["chat.run.completed", "chat.run.failed"]
    private let allEvents = ["chat.message.created", "chat.run.queued", "chat.run.started", "chat.tool.started", "chat.tool.completed", "chat.tool.failed", "chat.approval.requested", "chat.approval.resolved", "chat.clarification.requested", "chat.clarification.resolved", "chat.run.completed", "chat.run.failed"]
    var body: some View { NavigationStack { Form { Section("Destination") { TextField("Name", text: $name); TextField("HTTPS URL", text: $url).textInputAutocapitalization(.never).keyboardType(.URL); SecureField("Signing secret", text: $secret); Toggle("Enabled", isOn: $enabled); Stepper("Maximum retries: \(retries)", value: $retries, in: 0...10) }; Section("Payload") { Toggle("Include assistant content", isOn: $includeContent); Toggle("Include user content", isOn: $includeUser); Toggle("Allow private network", isOn: $privateNetwork) }; Section("Events") { ForEach(allEvents, id: \.self) { event in Button { if selected.contains(event) { selected.remove(event) } else { selected.insert(event) } } label: { HStack { Text(event); Spacer(); if selected.contains(event) { Image(systemName: "checkmark") } } }.foregroundStyle(.primary) } } }.navigationTitle(item == nil ? "New webhook" : "Edit webhook").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Save") { Task { await save() } }.disabled(name.isEmpty || url.isEmpty || selected.isEmpty) } }.onAppear { if let item { name = item.name; url = item.url; enabled = item.enabled; includeContent = item.includeContent; includeUser = item.includeUserContent; privateNetwork = item.privateNetwork; retries = item.retries; selected = Set(item.events) } } } }
    private func save() async { do { try await store.api.saveWebhook(item, name: name, url: url, secret: secret, events: selected.sorted(), profiles: item?.profiles ?? [], enabled: enabled, includeContent: includeContent, includeUserContent: includeUser, privateNetwork: privateNetwork, retries: retries); await reload(); dismiss() } catch { store.errorMessage = error.localizedDescription } }
}

struct RuntimeVersionsView: View {
    @EnvironmentObject private var store: AppStore
    @State private var status: RuntimeVersionStatus?; @State private var jobs: [JSON] = []; @State private var source = "cf"; @State private var working = ""
    var body: some View { List { if let status { Section("Active") { LabeledContent("Platform", value: status.platform); LabeledContent("Hermes runtime", value: status.activeRuntime); LabeledContent("Studio Web UI", value: status.activeWebUI); if !status.runtimeError.isEmpty { Text(status.runtimeError).foregroundStyle(.red) }; Button("Restart Studio") { Task { await restart() } }.disabled(!working.isEmpty) }; versions(title: "Hermes runtimes", kind: "runtime", installed: status.installedRuntime, remote: status.remoteRuntime, active: status.activeRuntime); versions(title: "Studio Web UI", kind: "webui", installed: status.installedWebUI, remote: status.remoteWebUI, active: status.activeWebUI); if !jobs.isEmpty { Section("Downloads") { ForEach(jobs.indices, id: \.self) { index in let job = jobs[index]; VStack(alignment: .leading) { HStack { Text(job.string("version")).font(.headline); Spacer(); Text(job.string("status")).foregroundStyle(job.string("status") == "failed" ? Color.red : Color.secondary) }; ProgressView(value: job.double("percent"), total: 100); Text(job.string("message", "error")).font(.caption).foregroundStyle(.secondary) } } } } } else { ProgressView() } }.navigationTitle("Runtime Versions").toolbar { ToolbarItem(placement: .topBarTrailing) { Picker("Source", selection: $source) { Text("Cloudflare").tag("cf"); Text("GitHub").tag("github") } } }.task { await load() }.refreshable { await load() } }
    private func versions(title: LocalizedStringKey, kind: String, installed: [JSON], remote: [String], active: String) -> some View { Section(title) { ForEach(installed.indices, id: \.self) { i in let row = installed[i], version = row.string("version"); HStack { VStack(alignment: .leading) { Text(version).font(.headline); Text(row.string("directory")).font(.caption2).foregroundStyle(.secondary).lineLimit(1) }; Spacer(); if version == active || row.bool("active") { StatusPill(text: "Active", color: .green) } else { Menu { Button("Activate") { Task { await activate(version, kind) } }; Button("Delete", role: .destructive) { Task { await delete(version, kind) } } } label: { Image(systemName: "ellipsis.circle") } } } }; ForEach(remote.filter { version in !installed.contains(where: { $0.string("version") == version }) }, id: \.self) { version in HStack { Text(version); Spacer(); Button("Download") { Task { await download(version, kind) } }.disabled(!working.isEmpty) } } } }
    private func load() async { do { status = try await store.api.runtimeVersions(); jobs = try await store.api.runtimeJobs() } catch { store.errorMessage = error.localizedDescription } }
    private func download(_ version: String, _ kind: String) async { working = version; do { try await store.api.downloadVersion(version, kind: kind, source: source); store.notify(String(localized: "Download started")); await load() } catch { store.errorMessage = error.localizedDescription }; working = "" }
    private func activate(_ version: String, _ kind: String) async { working = version; do { try await store.api.activateVersion(version, kind: kind); await load() } catch { store.errorMessage = error.localizedDescription }; working = "" }
    private func delete(_ version: String, _ kind: String) async { do { try await store.api.deleteVersion(version, kind: kind); await load() } catch { store.errorMessage = error.localizedDescription } }
    private func restart() async { working = "restart"; do { try await store.api.restartVersionedWebUI(); store.notify(String(localized: "Restart requested")) } catch { store.errorMessage = error.localizedDescription }; working = "" }
}

/// Settings → Tools → Theme (`views/hermes/ThemeView.vue`): the server-side
/// theme and background of the profile. The local light/dark preference is a
/// different thing (Settings → Display, and the footer chip) and is never
/// called "Theme".
struct ThemeView: View {
    @EnvironmentObject private var store: AppStore
    @State private var settings: ThemeSettings?; @State private var fontSize = 16.0; @State private var textColor = ""; @State private var accentColor = ""; @State private var importing = false; @State private var saving = false
    private let palette = ["#7C3AED", "#2563EB", "#0891B2", "#059669", "#D97706", "#DC2626", "#DB2777"]
    var body: some View { Form { Section("Typography") { Slider(value: $fontSize, in: 12...24, step: 1); LabeledContent("Font size", value: "\(Int(fontSize)) pt"); TextField("Text color (hex)", text: $textColor).textInputAutocapitalization(.characters) }; Section("Accent palette") { LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 7)) { ForEach(palette, id: \.self) { hex in Button { accentColor = hex } label: { Circle().fill(Color(hex: hex) ?? .accentColor).frame(width: 34, height: 34).overlay { if accentColor.uppercased() == hex { Image(systemName: "checkmark").foregroundStyle(.white).font(.caption.bold()) } } }.buttonStyle(.plain) } }; TextField("Accent color (hex)", text: $accentColor).textInputAutocapitalization(.characters) }; Section("Background") { if let settings, !settings.background.isEmpty { LabeledContent("Current", value: settings.background.string("name")); Button("Remove background", role: .destructive) { Task { await removeBackground() } } }; Button("Choose background image") { importing = true } }; Section { Button("Save theme") { Task { await save() } }.disabled(saving) } }.navigationTitle(NavDestination.theme.title).navigationBarTitleDisplayMode(.inline).task { await load() }.fileImporter(isPresented: $importing, allowedContentTypes: [.image]) { result in if case let .success(url) = result { Task { await upload(url) } } } }
    private func load() async { do { let value = try await store.api.themeSettings(); settings = value; fontSize = value.fontSize == 0 ? 16 : value.fontSize; textColor = value.textColor; accentColor = value.accentColor } catch { store.errorMessage = error.localizedDescription } }
    private func save() async { saving = true; do { settings = try await store.api.saveTheme(fontSize: fontSize, textColor: textColor.nilIfEmpty, accentColor: accentColor.nilIfEmpty); store.notify(String(localized: "Theme saved")) } catch { store.errorMessage = error.localizedDescription }; saving = false }
    private func upload(_ url: URL) async { let access = url.startAccessingSecurityScopedResource(); defer { if access { url.stopAccessingSecurityScopedResource() } }; do { let data = try Data(contentsOf: url); try await store.api.uploadThemeBackground(data: data, name: url.lastPathComponent, mime: UTType(filenameExtension: url.pathExtension)?.preferredMIMEType ?? "image/jpeg"); await load() } catch { store.errorMessage = error.localizedDescription } }
    private func removeBackground() async { do { try await store.api.deleteThemeBackground(); await load() } catch { store.errorMessage = error.localizedDescription } }
}

private extension Color { init?(hex: String) { let value = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#")); guard value.count == 6, let number = Int(value, radix: 16) else { return nil }; self.init(red: Double((number >> 16) & 255) / 255, green: Double((number >> 8) & 255) / 255, blue: Double(number & 255) / 255) } }

// The Agents screen moved to `Features/Agents/AgentManagerView.swift`. The
// version that lived here listed five hardcoded agents and could not be
// opened; the replacement renders whatever `GET /api/agents/status` returns
// and gives every agent its own screen.

struct GlobalAgentView: View {
    @EnvironmentObject private var store: AppStore
    @State private var sessions: [SessionSummary] = []
    @State private var loading = true
    private var freshSession: SessionSummary { SessionSummary(["id": UUID().uuidString, "title": String(localized: "New global session"), "profile": store.selectedProfile, "source": "global_agent", "agent": "ekko-agent"], profile: store.selectedProfile) }
    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Label(NavDestination.globalAgent.label, systemImage: "globe.desk.fill").font(.headline)
                    Text("Control Studio's always-available global agent and return to its sessions from any device.").font(.subheadline).foregroundStyle(.secondary)
                    NavigationLink { ConversationView(session: freshSession) } label: { Label("Start global session", systemImage: "plus.bubble.fill") }.buttonStyle(.borderedProminent)
                }.padding(.vertical, 6)
            }
            Section("Global sessions") {
                if loading { ProgressView() }
                else if sessions.isEmpty { ContentUnavailableView("No global sessions", systemImage: "globe") }
                ForEach(sessions) { session in
                    NavigationLink { ConversationView(session: session) } label: {
                        VStack(alignment: .leading, spacing: 4) { Text(session.title).font(.headline); HStack { Text(session.profile); if session.messageCount > 0 { Text("· \(session.messageCount) messages") } }.font(.caption).foregroundStyle(.secondary); if !session.preview.isEmpty { Text(session.preview).font(.subheadline).foregroundStyle(.secondary).lineLimit(2) } }
                    }
                }
            }
        }.listStyle(.insetGrouped).navigationTitle(NavDestination.globalAgent.title).navigationBarTitleDisplayMode(.inline).refreshable { await load() }.task { await load() }
        .toolbar { ToolbarItem(placement: .topBarTrailing) { Button { Task { await load() } } label: { Image(systemName: "arrow.clockwise") } } }
    }
    private func load() async { loading = true; do { sessions = try await store.api.sessions(profile: store.selectedProfile).filter { $0.source == "global_agent" } } catch { store.errorMessage = error.localizedDescription }; loading = false }
}

struct StudioFilesView: View {
    @EnvironmentObject private var store: AppStore
    let path: String
    @State private var files: [StudioFileItem] = []; @State private var loading = true; @State private var importing = false; @State private var newFolder = false; @State private var folderName = ""; @State private var actionFile: StudioFileItem?; @State private var actionName = ""
    init(path: String = "") { self.path = path }
    var body: some View { List { if loading { ProgressView() }; ForEach(files) { file in Group { if file.isDirectory { NavigationLink { StudioFilesView(path: file.path) } label: { row(file) } } else { NavigationLink { StudioFileEditor(file: file) } label: { row(file) } } }.swipeActions { Button(role: .destructive) { Task { await delete(file) } } label: { Label("Delete", systemImage: "trash") }; Button { actionFile = file; actionName = file.path } label: { Label("More", systemImage: "ellipsis") } } } }.navigationTitle(path.isEmpty ? NavDestination.files.title : URL(fileURLWithPath: path).lastPathComponent).navigationBarTitleDisplayMode(.inline).overlay { if !loading && files.isEmpty { ContentUnavailableView("Empty folder", systemImage: "folder") } }.task { await load() }.refreshable { await load() }.toolbar { ToolbarItemGroup(placement: .topBarTrailing) { Button { newFolder = true } label: { Image(systemName: "folder.badge.plus") }; Button { importing = true } label: { Image(systemName: "square.and.arrow.down") } } }.fileImporter(isPresented: $importing, allowedContentTypes: [.item], allowsMultipleSelection: true) { result in if case let .success(urls) = result { Task { await upload(urls) } } }.alert("New folder", isPresented: $newFolder) { TextField("Name", text: $folderName); Button("Create") { Task { await mkdir() } }; Button("Cancel", role: .cancel) {} }.confirmationDialog("File actions", isPresented: Binding(get: { actionFile != nil }, set: { if !$0 { actionFile = nil } })) { if let file = actionFile { Button("Rename or move") { actionName = file.path; renamePrompt = true }; Button("Copy") { actionName = file.path + "-copy"; copyPrompt = true }; Button("Open externally") { Task { await openExternally(file) } } }; Button("Cancel", role: .cancel) {} }.alert("Rename or move", isPresented: $renamePrompt) { TextField("Path", text: $actionName); Button("Save") { Task { await rename() } }; Button("Cancel", role: .cancel) {} }.alert("Copy file", isPresented: $copyPrompt) { TextField("Destination path", text: $actionName); Button("Copy") { Task { await copy() } }; Button("Cancel", role: .cancel) {} }.quickLookPreview($previewURL) }
    @State private var renamePrompt = false; @State private var copyPrompt = false; @State private var previewURL: URL?
    /// Downloads with the bearer token in the header (never in the URL) and opens the local copy in Quick Look.
    private func openExternally(_ file: StudioFileItem) async { actionFile = nil; do { previewURL = try await store.api.downloadStudioFile(file.path, profile: store.selectedProfile) } catch { store.errorMessage = error.localizedDescription } }
    private func row(_ file: StudioFileItem) -> some View { HStack { Image(systemName: file.isDirectory ? "folder.fill" : "doc.fill").foregroundStyle(file.isDirectory ? .blue : .secondary); VStack(alignment: .leading) { Text(file.name); if !file.isDirectory { Text(ByteCountFormatter.string(fromByteCount: Int64(file.size), countStyle: .file)).font(.caption).foregroundStyle(.secondary) } } } }
    private func joined(_ name: String) -> String { path.isEmpty ? name : "\(path)/\(name)" }
    private func load() async { loading = true; do { files = try await store.api.studioFiles(path: path, profile: store.selectedProfile) } catch { store.errorMessage = error.localizedDescription }; loading = false }
    private func mkdir() async { do { try await store.api.mkdirStudioFile(joined(folderName), profile: store.selectedProfile); folderName = ""; await load() } catch { store.errorMessage = error.localizedDescription } }
    private func delete(_ file: StudioFileItem) async { do { try await store.api.deleteStudioFile(file.path, recursive: file.isDirectory, profile: store.selectedProfile); await load() } catch { store.errorMessage = error.localizedDescription } }
    private func rename() async { guard let file = actionFile else { return }; do { try await store.api.renameStudioFile(file.path, to: actionName, profile: store.selectedProfile); actionFile = nil; await load() } catch { store.errorMessage = error.localizedDescription } }
    private func copy() async { guard let file = actionFile else { return }; do { try await store.api.copyStudioFile(file.path, to: actionName, profile: store.selectedProfile); actionFile = nil; await load() } catch { store.errorMessage = error.localizedDescription } }
    private func upload(_ urls: [URL]) async { for url in urls { let scoped = url.startAccessingSecurityScopedResource(); defer { if scoped { url.stopAccessingSecurityScopedResource() } }; if let data = try? Data(contentsOf: url) { await store.attempt({ try await store.api.uploadStudioFile(data: data, name: url.lastPathComponent, mime: "application/octet-stream", path: path, profile: store.selectedProfile) }) } }; await load() }
}

private struct StudioFileEditor: View { @EnvironmentObject var store: AppStore; let file: StudioFileItem; @State var content = ""; @State var loading = true; @State var sharedURL: URL?; @State var downloading = false
    /// The share sheet needs a local file: download it first with the bearer token in the header.
    private func prepareShare() async { downloading = true; defer { downloading = false }; do { sharedURL = try await store.api.downloadStudioFile(file.path, profile: store.selectedProfile) } catch { store.errorMessage = error.localizedDescription } }
    var body: some View { TextEditor(text: $content).font(.body.monospaced()).padding(6).navigationTitle(file.name).navigationBarTitleDisplayMode(.inline).overlay { if loading { ProgressView() } }.task { do { content = try await store.api.readStudioFile(file.path, profile: store.selectedProfile) } catch { store.errorMessage = error.localizedDescription }; loading = false }.toolbar { ToolbarItemGroup(placement: .topBarTrailing) { if let sharedURL { ShareLink(item: sharedURL) { Image(systemName: "square.and.arrow.up") } } else { Button { Task { await prepareShare() } } label: { Image(systemName: downloading ? "hourglass" : "square.and.arrow.up") }.disabled(downloading) }; Button("Save") { Task { do { try await store.api.writeStudioFile(file.path, content: content, profile: store.selectedProfile); store.notify(String(localized: "File saved")) } catch { store.errorMessage = error.localizedDescription } } } } } }
}

struct StudioLogsView: View { @EnvironmentObject var store: AppStore; @State var files: [StudioLogFile] = []
    var body: some View { List(files) { file in NavigationLink { StudioLogDetail(file: file) } label: { VStack(alignment: .leading) { Text(file.name).font(.headline); HStack { Text(file.size); Text("·"); Text(file.modified) }.font(.caption).foregroundStyle(.secondary) } } }.navigationTitle(NavDestination.logs.title).navigationBarTitleDisplayMode(.inline).task { files = (await store.attempt({ try await store.api.logFiles() })) ?? files }.refreshable { files = (await store.attempt({ try await store.api.logFiles() })) ?? files } }
}
private struct StudioLogDetail: View { @EnvironmentObject var store: AppStore; let file: StudioLogFile; @State var entries: [StudioLogEntry] = []; @State var search = ""; @State var level = ""
    var body: some View { List { SearchBar(text: $search); Picker("Level", selection: $level) { Text("All").tag(""); ForEach(["error","warn","info","debug"], id: \.self) { Text($0.capitalized).tag($0) } }.pickerStyle(.segmented); ForEach(entries) { entry in VStack(alignment: .leading, spacing: 4) { HStack { StatusPill(text: entry.level, color: entry.level == "error" ? .red : (entry.level == "warn" ? .orange : .blue)); Text(entry.timestamp).font(.caption2).foregroundStyle(.secondary) }; Text(entry.message.nilIfEmpty ?? entry.raw).font(.caption.monospaced()).textSelection(.enabled) } } }.navigationTitle(file.name).task(id: "\(search)|\(level)") { try? await Task.sleep(for: .milliseconds(250)); entries = (await store.attempt({ try await store.api.logEntries(file.name, text: search, level: level) })) ?? entries } }
}

}
